name: Github Build

on:
  push:
    branches: [master, develop]
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    env:
      BRANCH: ${{github.ref}}
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci

      - name: Bootstrap
        run: npm run bs

      - name: Linting
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build --if-present

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: dev-travis
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
