name: Dev Test & Build

on:
  push:
    branches: [develop]
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        if: ${{ always() }}
        run: npm i

      - name: Lint
        if: ${{ always() }}
        run: npm run lint

      - name: Build
        if: ${{ always() }}
        run: npm run build

      - name: Local Test
        if: ${{ always() }}
        run: npm run lh

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: github-builds
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
