name: PR Test & Report

on:
  pull_request:
    branches:
      [
        main,
        develop,
        /^release/.*$/,
        /^feature/.*$/,
        /^bugfix/.*$/,
        /^hotfix/.*$/,
        /^support/.*$/,
      ]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "**/*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        if: ${{ always() }}
        run: npm install

      - name: Lint
        if: ${{ always() }}
        run: npm run lint

      - name: Build
        if: ${{ always() }}
        run: npm run build

      - name: Local Test
        if: ${{ always() }}
        run: npm run lh
