# see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages
name: Github Publish Package

on:
  push:
    tags:
      - "v*"

jobs:
  build-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://npm.pkg.github.com"
          scope: "@ejnkr"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Publish package
        run: npm publish

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: github-builds
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
